---
apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: challengize-exporter
  name: challengize-exporter
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: challengize-exporter
    deploymentconfig: challengize-exporter
  strategy:
    activeDeadlineSeconds: 21600
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Recreate
  template:
    metadata:
      labels:
        app: challengize-exporter
        deploymentconfig: challengize-exporter
    spec:
      containers:
        - name: challengize-exporter
          image: docker-registry.default.svc:5000/devops-challengize-exporter-prod/challengize-exporter:20190417
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          env:
            - name: JSESSIONID
              valueFrom:
                secretKeyRef:
                  key: JSESSIONID
                  name: challengize-credentials
            - name: REMEMBER
              valueFrom:
                secretKeyRef:
                  key: REMEMBER
                  name: challengize-credentials
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  labels:
    app: challengize-exporter
  name: challengize-exporter
spec:
  ports:
  - port: 8080
    name: metrics
  clusterIP: None
  selector:
    app: challengize-exporter
---
apiVersion: network.openshift.io/v1
kind: EgressNetworkPolicy
metadata:
  name: challengize-egress
spec:
  egress:
    - to:
        dnsName: www.challengize.com
      type: Allow
    - to:
        cidrSelector: 10.0.0.0/8
      type: Deny
    - to:
        cidrSelector: 192.168.0.0/16
      type: Deny
    - to:
        cidrSelector: 169.254.169.254/32
      type: Deny